### ISSUE TITLE
rabbitmq-server job pre-start script fail during deployment

### ISSUE THREAD

**Issue by wenxin-liu** [pivotal-cf/cf-rabbitmq-release#114] opened 2018-11-15 17:21 UTC
Hey everyone,

We're trying to deploy a new rabbitmq deployment. Using the latest version v253.0.0, we interpolated the manifest as per the installation instructions in the readme, we hit this error:

```
16:52:23 | Preparing deployment: Preparing deployment
16:52:24 | Warning: IP address not available for the link provider instance: rmq/89c5ac2f-39bf-4acf-a187-676397e7fff1
16:52:24 | Warning: IP address not available for the link provider instance: rmq/2de67b09-8bc1-4f4e-90ad-dc775848cc3a
16:52:24 | Warning: IP address not available for the link provider instance: rmq/5e4a215e-0d45-429f-b5ba-64e3a8f4c541
16:52:24 | Warning: IP address not available for the link provider instance: rmq/89c5ac2f-39bf-4acf-a187-676397e7fff1
16:52:24 | Warning: IP address not available for the link provider instance: rmq/2de67b09-8bc1-4f4e-90ad-dc775848cc3a
16:52:24 | Warning: IP address not available for the link provider instance: rmq/5e4a215e-0d45-429f-b5ba-64e3a8f4c541
16:52:24 | Warning: IP address not available for the link provider instance: nats/0686302f-a30a-43b9-b5d4-2a0268835ff7
16:52:24 | Warning: IP address not available for the link provider instance: nats/e8b2af09-e742-457a-9e58-4c59e6671521
16:52:24 | Warning: IP address not available for the link provider instance: nats/ed8fd81a-4839-4b15-af45-55255da6b882
16:52:24 | Preparing deployment: Preparing deployment (00:00:01)
16:52:26 | Preparing package compilation: Finding packages to compile (00:00:00)
16:52:26 | Compiling packages: erlang/58d3f5df2010e2843e46aca77719f6e1d5a9c2eac6f3a5e3a28307a766cbfd38 (00:10:04)
17:03:37 | Creating missing vms: rmq/2de67b09-8bc1-4f4e-90ad-dc775848cc3a (2)
17:03:37 | Creating missing vms: rmq/89c5ac2f-39bf-4acf-a187-676397e7fff1 (0)
17:03:37 | Creating missing vms: rmq/5e4a215e-0d45-429f-b5ba-64e3a8f4c541 (1)
17:03:37 | Creating missing vms: haproxy/aa0f1e50-94a2-4038-bf67-40617c6a40b5 (0)
17:04:15 | Creating missing vms: rmq/2de67b09-8bc1-4f4e-90ad-dc775848cc3a (2) (00:00:38)
17:04:18 | Creating missing vms: rmq/5e4a215e-0d45-429f-b5ba-64e3a8f4c541 (1) (00:00:41)
17:04:20 | Creating missing vms: rmq/89c5ac2f-39bf-4acf-a187-676397e7fff1 (0) (00:00:43)
17:04:21 | Creating missing vms: haproxy/aa0f1e50-94a2-4038-bf67-40617c6a40b5 (0) (00:00:44)
17:04:25 | Updating instance haproxy: haproxy/aa0f1e50-94a2-4038-bf67-40617c6a40b5 (0) (canary)
17:04:25 | Updating instance rmq: rmq/89c5ac2f-39bf-4acf-a187-676397e7fff1 (0) (canary) (00:00:38)
            L Error: Action Failed get_task: Task ce089a46-f3fe-4a2a-5ffb-f85d15a2f8be result: 1 of 1 pre-start scripts failed. Failed Jobs: rabbitmq-server.
17:05:12 | Updating instance haproxy: haproxy/aa0f1e50-94a2-4038-bf67-40617c6a40b5 (0) (canary) (00:00:47)

17:05:12 | Error: Action Failed get_task: Task ce089a46-f3fe-4a2a-5ffb-f85d15a2f8be result: 1 of 1 pre-start scripts failed. Failed Jobs: rabbitmq-server.
```

When I ssh into rmq/89c5ac2f-39bf-4acf-a187-676397e7fff1 and check the logs, in pre-start.stderr.log I see the following error:

```
2018-11-15 17:05:00 inet_config: parse error in ~ts~n^M
        2018-11-15 17:05:01 inet_config: parse error in ~ts~n^M
        comm: file 1 is not in sorted order
```

And in pre-start.stdout.log, I see:
```
=ERROR REPORT==== 15-Nov-2018::17:05:00 ===
inet_config: parse error in /var/vcap/store/rabbitmq/erl_inetrc
```

I tried deploying v252.0.0 and also got the same error. Could you help with what's gone wrong here?

**Comment by blgm** [comment] 2018-12-04 17:55
@wenxin-liu, which stemcell are you using?

The error message seems to come from deep within Erlang: https://github.com/erlang/otp/blob/master/lib/kernel/src/inet_config.erl#L260
@hairyhum @michaelklishin, would you expect the `~ts~n^M` to be interpolated into something more meaningful?  It looks like an attempt to do a `printf` equivalent.

My guess would be that this is caused by parsing the file `/var/vcap/store/rabbitmq/erl_inetrc`.  A good one looks like:
```
{host, {10,0,4,10}, ["eaee322bf5da343c18b95dcb08dabad5"]}.
{host, {10,0,4,11}, ["dce07ff98e3da0dcee2c738aabbb8f1e"]}.
{host, {10,0,4,12}, ["881881c9ed15cef3c0417de34b239e29"]}.
{lookup, [file, native]}.
```
What does your file look like?

**Comment by wenxin-liu** [comment] 2018-12-05 10:18
Hey @blgm and everyone,

Thanks for your suggestion, we've just recently managed to work around the problem, and indeed as you pointed out, it was to do with a syntax error in the erl_inetrc file. We're currently using ubuntu-trusty/v3586.36.

Although we've managed to work around the issue, although the core problem is not fixed. The core problem is: The release does not work when using a dynamic bosh network.

We are hosted in GCP and therefore use a dynamic network (defers IP selection to the IaaS provider). During deployment of the rmq release, it fails because the erl_inetrc file created needs to have the hosts information in the format of {host, IP, alias}. But when using a dynamic network, during deployment bosh only 'knows' the DNS names of the vms in the cluster, not the IPs. As a result, the resulting erl_inetrc file is in the format of {host, DNS name, alias}. The pre-start script then fails, and we get an error that the file cannot be parsed because it has a syntax error and it's not sorted in the right order. We discovered that if we switch to using a manual network, because bosh assigns the IPs, it also 'knows' the IPs and is able to put them into the erl_inetrc file as required. The resulting erl_inetrc file has the correct format, that is {host, IP, alias}. This works around the issue. But ideally this release should either fetch the IPs in a different way (currently the release uses Bosh [links](https://github.com/pivotal-cf/cf-rabbitmq-release/blob/50e4d95d63552ed053344edaa0af9127fa5f0045/jobs/rabbitmq-server/templates/rabbitmq-config-vars.bash.erb#L10)), or even better, not use IPs at all but DNS addresses (as using IPs means tightly coupled).

**Comment by hairyhum** [comment] 2018-12-11 12:46
@blgm I'm not sure how the log message ends up in the `stderr`, but it seems like it's formatted correctly to the `stdout`.

**Comment by nodo** [comment] 2019-01-17 14:12
Thanks for raising this and for sharing your investigation @wenxin-liu !

We have [added](https://github.com/pivotal-cf/cf-rabbitmq-release/commit/29bf50fa8596731850bc0207f68d5de59ce4c8d9) a note to the README, mentioning that the release has only been tested using "manual" networks. We are planning to add support for BOSH DNS soon, hopefully after that we will be able to support other network types as well.

We are going to close the issue for now. Feel free to re-open if you have further questions.

@ferozjilla and @nodo

**Closed by nodo** 2019-01-17 14:12 UTC
Labels: in progress

**Comment by wenxin-liu** [comment] 2019-01-21 16:38
Thanks @nodo !
